import { useEffect } from 'react';
import { useNavigate, useRouteError } from 'react-router-dom';

export function NotFound() {
    return (
        <div style={{ padding: '2rem', textAlign: 'center' }}>
            <h1>404 - P치gina no encontrada</h1>
            <p>Lo sentimos, la p치gina que buscas no existe.</p>
        </div>
    );
}

export function ErrorPage() {
    const error = useRouteError() as Error;
    const navigate = useNavigate();
    return (
        <div className="h-screen flex flex-col items-center justify-center text-center p-4">
            <h1 className="text-3xl font-bold mb-4">丘멆잺 Ha ocurrido un error</h1>
            <p>{error?.message || 'Ha ocurrido un error inesperado.'}</p>
            <button className="mt-4 px-4 py-2 bg-blue-600 text-white rounded" onClick={() => navigate('/')}>
                Recargar p치gina
            </button>
        </div>
    );
}
export function FalloFetch() {
    useEffect(() => {
        throw new Error('游눤 Error de prueba');
    }, []);

    // Aunque nunca se renderice, el componente debe devolver algo
    return <div>Esto nunca deber칤a verse 游땐</div>;
}
export function FalloRender() {
    // Error directo en el render
    throw new Error('游눤 Error de prueba en render');

    return <div>Esto nunca se ver치</div>;
}
